"""Regenerate INDEX.md from tracked files.

Usage:
    python tools/update_index.py          # write INDEX.md
    python tools/update_index.py --check  # exit 1 if INDEX.md would change

INDEX.md is regenerated by the pre-commit hook in a convergence loop until
git hash-object INDEX.md is stable. The self-reference (INDEX.md describes
itself, including its line count) typically converges in 1-2 iterations.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INDEX_PATH = REPO_ROOT / "INDEX.md"

EXCLUDE_DIRS = {
    ".git",
    ".vscode",
    ".claude",
    "__pycache__",
    ".pytest_cache",
    ".ruff_cache",
    ".mypy_cache",
}
EXCLUDE_SUFFIXES = {".pyc"}


def tracked_files() -> list[Path]:
    """Return repo files known to git, plus INDEX.md if it exists locally."""
    out = subprocess.check_output(["git", "ls-files"], cwd=REPO_ROOT, text=True)
    paths: list[Path] = []
    for line in out.splitlines():
        p = REPO_ROOT / line
        if any(part in EXCLUDE_DIRS for part in p.parts):
            continue
        if p.suffix in EXCLUDE_SUFFIXES:
            continue
        if not p.is_file():
            continue
        paths.append(p)
    if INDEX_PATH.exists() and INDEX_PATH not in paths:
        paths.append(INDEX_PATH)
    return sorted(paths, key=lambda p: p.relative_to(REPO_ROOT).as_posix())


def purpose_line(path: Path) -> str:
    """One-line description of a file's purpose. Best-effort, heuristic."""
    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return "(binary)"
    suffix = path.suffix.lower()

    if suffix == ".md":
        for line in text.splitlines():
            stripped = line.strip().lstrip("#").strip()
            if stripped:
                return stripped
    elif suffix == ".py":
        m = re.search(r'^"""(.+?)"""', text, re.DOTALL | re.MULTILINE)
        if m:
            first = m.group(1).strip().splitlines()[0].strip()
            if first:
                return first
        for line in text.splitlines():
            stripped = line.strip()
            if stripped.startswith("# Purpose:"):
                return stripped.removeprefix("# Purpose:").strip()
    elif suffix in {".sh", ".bash"}:
        for line in text.splitlines()[:5]:
            stripped = line.lstrip("#").strip()
            if stripped and not stripped.startswith("/"):
                return stripped
    elif suffix in {".yml", ".yaml"}:
        for line in text.splitlines()[:3]:
            if line.startswith("name:"):
                return line.split(":", 1)[1].strip().strip('"\'')
        for line in text.splitlines()[:3]:
            stripped = line.lstrip("#").strip()
            if stripped:
                return stripped
    elif suffix == ".json":
        return "(JSON config)"
    elif suffix == ".toml":
        return "(TOML config)"
    elif suffix == ".txt":
        for line in text.splitlines()[:3]:
            stripped = line.lstrip("#").strip()
            if stripped:
                return stripped
    return ""


def file_stats(path: Path) -> tuple[int, int]:
    """Return (line_count, byte_count) for a file."""
    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        data = path.read_bytes()
        return 0, len(data)
    if not text:
        return 0, 0
    lines = text.count("\n") + (0 if text.endswith("\n") else 1)
    return lines, len(text.encode("utf-8"))


def build_index(files: list[Path]) -> str:
    lines = [
        "# Repository Index",
        "",
        "Auto-generated by `tools/update_index.py`. Do not edit by hand.",
        "",
        "| Path | Lines | Bytes | Purpose |",
        "| --- | ---: | ---: | --- |",
    ]
    for f in files:
        rel = f.relative_to(REPO_ROOT).as_posix()
        n_lines, n_bytes = file_stats(f)
        purpose = purpose_line(f).replace("|", "\\|")
        lines.append(f"| `{rel}` | {n_lines} | {n_bytes} | {purpose} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="exit 1 if INDEX.md would change")
    args = parser.parse_args()

    content = build_index(tracked_files())

    if args.check:
        existing = ""
        if INDEX_PATH.exists():
            # Read as bytes then decode to avoid universal-newlines translation
            # masking CRLF/LF mismatches in the on-disk file.
            existing = INDEX_PATH.read_bytes().decode("utf-8")
        if existing != content:
            print("INDEX.md is out of date. Run: python tools/update_index.py", file=sys.stderr)
            return 1
        return 0

    # newline="\n" so the file is byte-identical on Windows and Linux. .gitattributes
    # would normalize on stage, but having LF on disk too lets the convergence loop
    # detect "no change" via git hash-object instead of fighting line-ending churn.
    INDEX_PATH.write_text(content, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
